## docker-compose.yml

version: "3.7"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - test
    init: true

  web:
    image: test-web:latest
    build: .
    environment:
      - REDIS_HOST=redis
    ports:
      - 5000:5000
    networks:
      - test
    depends_on:
      - redis
    init: true
networks:
  test:
